import type { TeacherSchedule } from "./src/types";

export const data: TeacherSchedule = {
  Alemanno: [
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "5AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "5AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "5AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "5AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "3AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "3AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "3AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "3AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "3AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
  ],
  Chiocchetti: [
    {
      MATERIA: "Inglese",
      CLASSE: "1AS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "3ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "2AS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "5ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "2AS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "4ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "4AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "3AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "5ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "5AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "3AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "5AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "1AS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "3ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "4ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "4AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
  ],
  Rossi: [
    {
      MATERIA: "Storia, Cittadinanza e costituzione",
      CLASSE: "2AS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "2AS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "4AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Storia, Cittadinanza e costituzione",
      CLASSE: "5AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
  ],
};
