import type { TeacherSchedule } from "./src/types";

export const data: TeacherSchedule = {
  alemanno_giancarlo: [
    {
      MATERIA: "Informatica",
      CLASSE: "3AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "3AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "3AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "3AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "3AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "4AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "5AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "5AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "5AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Informatica",
      CLASSE: "5AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
  ],
  // Cammarota: [
  //   {
  //     MATERIA: "Scienze della Terra e Biologia",
  //     CLASSE: "1AS",
  //     GIORNO: "Mercoledì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Scienze della Terra e Biologia",
  //     CLASSE: "1AS",
  //     GIORNO: "Giovedì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Scienze della Terra e Biologia",
  //     CLASSE: "1AS",
  //     GIORNO: "Giovedì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  // ],
  canino_massimo: [
    {
      MATERIA: "Matematica",
      CLASSE: "1AS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "1AS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "1AS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "2AS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "2AS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "2AS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "3ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "3ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "3ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "4ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "4ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "4ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "5ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "5ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "5ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "5AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "5AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "5AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
  ],
  // Casillo: [
  //   {
  //     MATERIA: "Scienze Integrate - Chimica",
  //     CLASSE: "1AS",
  //     GIORNO: "Mercoledì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "4ACS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "20:00",
  //     ORA_FINE: "20:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "4ACS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "20:50",
  //     ORA_FINE: "21:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "4ACS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "21:50",
  //     ORA_FINE: "22:40",
  //   },
  //   {
  //     MATERIA: "Chimica Organica e Biochimica",
  //     CLASSE: "4ACS",
  //     GIORNO: "Mercoledì",
  //     ORA_INIZIO: "20:50",
  //     ORA_FINE: "21:50",
  //   },
  //   {
  //     MATERIA: "Chimica Organica e Biochimica",
  //     CLASSE: "4ACS",
  //     GIORNO: "Mercoledì",
  //     ORA_INIZIO: "21:50",
  //     ORA_FINE: "22:40",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "5ACS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "20:50",
  //     ORA_FINE: "21:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "5ACS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "21:50",
  //     ORA_FINE: "22:40",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "5ACS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "20:00",
  //     ORA_FINE: "20:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "5ACS",
  //     GIORNO: "Mercoledì",
  //     ORA_INIZIO: "20:00",
  //     ORA_FINE: "20:50",
  //   },
  //   {
  //     MATERIA: "Chimica Organica e Biochimica",
  //     CLASSE: "5ACS",
  //     GIORNO: "Venerdì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  // ],
  chiocchetti_gudrun: [
    {
      MATERIA: "Inglese",
      CLASSE: "1AS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "1AS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "2AS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "2AS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "3ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "3ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "3AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "3AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "4ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "4ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "4AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "4AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "5ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "5ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "5AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Inglese",
      CLASSE: "5AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
  ],
  // Cimini: [
  //   {
  //     MATERIA: "Telecomunicazioni",
  //     CLASSE: "3AIS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Telecomunicazioni",
  //     CLASSE: "3AIS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  // ],
  // Colavitto: [
  //   {
  //     MATERIA: "Scienze Integrate - Fisica",
  //     CLASSE: "1AS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Scienze Integrate - Fisica",
  //     CLASSE: "1AS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  //   {
  //     MATERIA: "Scienze Integrate - Fisica",
  //     CLASSE: "2AS",
  //     GIORNO: "Giovedì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Scienze Integrate - Fisica",
  //     CLASSE: "2AS",
  //     GIORNO: "Giovedì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  // ],
  // Cupo: [
  //   {
  //     MATERIA: "Tecnologia e Tecniche di Rappresentazione Grafica",
  //     CLASSE: "1AS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  // ],
  // Fascetto: [
  //   {
  //     MATERIA: "Tecnologia e Tecniche di Rappresentazione Grafica",
  //     CLASSE: "1AS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Tecnologia e Tecniche di Rappresentazione Grafica",
  //     CLASSE: "1AS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  //   {
  //     MATERIA: "Tecnologia e Tecniche di Rappresentazione Grafica",
  //     CLASSE: "1AS",
  //     GIORNO: "Venerdì",
  //     ORA_INIZIO: "20:00",
  //     ORA_FINE: "20:50",
  //   },
  //   {
  //     MATERIA: "Tecnologia e Tecniche di Rappresentazione Grafica",
  //     CLASSE: "2AS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "20:00",
  //     ORA_FINE: "20:50",
  //   },
  //   {
  //     MATERIA: "Tecnologia e Tecniche di Rappresentazione Grafica",
  //     CLASSE: "2AS",
  //     GIORNO: "Venerdì",
  //     ORA_INIZIO: "20:50",
  //     ORA_FINE: "21:50",
  //   },
  //   {
  //     MATERIA: "Tecnologia e Tecniche di Rappresentazione Grafica",
  //     CLASSE: "2AS",
  //     GIORNO: "Venerdì",
  //     ORA_INIZIO: "21:50",
  //     ORA_FINE: "22:40",
  //   },
  // ],
  fezza_antonio: [
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "3AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "TPSIT",
      CLASSE: "3AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "3AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "3AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "TPSIT",
      CLASSE: "3AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "4AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "4AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "4AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "5AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "5AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Gestione di Progettazione e Organizzazione di Impresa",
      CLASSE: "5AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "5AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Gestione di Progettazione e Organizzazione di Impresa",
      CLASSE: "5AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
  ],
  // Giannini: [
  //   {
  //     MATERIA: "Telecomunicazioni",
  //     CLASSE: "4AIS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Telecomunicazioni",
  //     CLASSE: "4AIS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  // ],
  maggi_stefano: [
    {
      MATERIA: "Matematica",
      CLASSE: "3AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "3AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "3AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "4AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "4AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Matematica",
      CLASSE: "4AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
  ],
  // Malberti: [
  //   {
  //     MATERIA: "Scienze Integrate - Fisica",
  //     CLASSE: "1AS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Scienze Integrate - Fisica",
  //     CLASSE: "1AS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  //   {
  //     MATERIA: "Scienze Integrate - Fisica",
  //     CLASSE: "1AS",
  //     GIORNO: "Giovedì",
  //     ORA_INIZIO: "20:00",
  //     ORA_FINE: "20:50",
  //   },
  //   {
  //     MATERIA: "Scienze Integrate - Fisica",
  //     CLASSE: "2AS",
  //     GIORNO: "Giovedì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Scienze Integrate - Fisica",
  //     CLASSE: "2AS",
  //     GIORNO: "Giovedì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  // ],
  martino_tonino: [
    {
      MATERIA: "Scienze Integrate - Chimica",
      CLASSE: "1AS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Scienze Integrate - Chimica",
      CLASSE: "1AS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Scienze e Tecnologie Applicate",
      CLASSE: "2AS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Scienze e Tecnologie Applicate",
      CLASSE: "2AS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "3ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "3ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "3ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "3ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "4ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "4ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "4ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "4ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "5ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "5ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "5ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
  ],
  morossi_paola: [
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "1AS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "1AS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "1AS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "3ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "3ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "3ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "3ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "3ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "3AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "3AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "3AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "4ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "4ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "4ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "4ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "4ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "5ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "5ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "5ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "5ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "5ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
  ],
  nuzzo_francesco: [
    {
      MATERIA: "Tecnologia Informatica",
      CLASSE: "1AS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "3AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "TPSIT",
      CLASSE: "4AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "4AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "5AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Sistemi e Reti",
      CLASSE: "5AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "TPSIT",
      CLASSE: "5AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "TPSIT",
      CLASSE: "5AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
  ],
  // Pappalardo: [
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "3ACS",
  //     GIORNO: "Mercoledì",
  //     ORA_INIZIO: "20:50",
  //     ORA_FINE: "21:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "3ACS",
  //     GIORNO: "Mercoledì",
  //     ORA_INIZIO: "21:50",
  //     ORA_FINE: "22:40",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "3ACS",
  //     GIORNO: "Giovedì",
  //     ORA_INIZIO: "20:50",
  //     ORA_FINE: "21:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "3ACS",
  //     GIORNO: "Giovedì",
  //     ORA_INIZIO: "21:50",
  //     ORA_FINE: "22:40",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "3ACS",
  //     GIORNO: "Venerdì",
  //     ORA_INIZIO: "20:50",
  //     ORA_FINE: "21:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "4ACS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "20:00",
  //     ORA_FINE: "20:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "4ACS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "20:50",
  //     ORA_FINE: "21:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "4ACS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "21:50",
  //     ORA_FINE: "22:40",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "4ACS",
  //     GIORNO: "Giovedì",
  //     ORA_INIZIO: "21:50",
  //     ORA_FINE: "22:40",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "4ACS",
  //     GIORNO: "Venerdì",
  //     ORA_INIZIO: "20:00",
  //     ORA_FINE: "20:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "5ACS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "20:50",
  //     ORA_FINE: "21:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "5ACS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "21:50",
  //     ORA_FINE: "22:40",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "5ACS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "20:00",
  //     ORA_FINE: "20:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "5ACS",
  //     GIORNO: "Mercoledì",
  //     ORA_INIZIO: "20:00",
  //     ORA_FINE: "20:50",
  //   },
  //   {
  //     MATERIA: "Chimica Analitica e Strumentale",
  //     CLASSE: "5ACS",
  //     GIORNO: "Venerdì",
  //     ORA_INIZIO: "21:50",
  //     ORA_FINE: "22:40",
  //   },
  // ],
  prencipe_francesco: [
    {
      MATERIA: "Tecnologia Informatica",
      CLASSE: "1AS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Tecnologia Informatica",
      CLASSE: "1AS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Scienze e Tecnologie Applicate",
      CLASSE: "2AS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Scienze e Tecnologie Applicate",
      CLASSE: "2AS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "TPSIT",
      CLASSE: "4AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "TPSIT",
      CLASSE: "4AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "TPSIT",
      CLASSE: "5AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "TPSIT",
      CLASSE: "5AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "TPSIT",
      CLASSE: "5AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
  ],
  romano_francesco: [
    {
      MATERIA: "Scienze Integrate - Chimica",
      CLASSE: "2AS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "3ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Chimica Organica e Biochimica",
      CLASSE: "3ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Chimica Analitica e Strumentale",
      CLASSE: "3ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Chimica Analitica e Strumentale",
      CLASSE: "3ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Chimica Analitica e Strumentale",
      CLASSE: "3ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Chimica Analitica e Strumentale",
      CLASSE: "3ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "4ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "5ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "5ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
  ],
  rossi_alessandro: [
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "2AS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "2AS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "2AS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "2AS",
      GIORNO: "Martedì",
      ORA_INIZIO: "21:50",
      ORA_FINE: "22:40",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "2AS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "2AS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "3AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "3AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "4AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "4AIS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "4AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "4AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "4AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "5AIS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "5AIS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "5AIS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Lingua e Letteratura Italiana",
      CLASSE: "5AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Storia, Cittadinanza e Costituzione",
      CLASSE: "5AIS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
  ],
  saracino_luigi: [
    {
      MATERIA: "Scienze Integrate - Chimica",
      CLASSE: "2AS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Scienze Integrate - Chimica",
      CLASSE: "2AS",
      GIORNO: "Martedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Scienze Integrate - Chimica",
      CLASSE: "2AS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:50",
      ORA_FINE: "21:50",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "3ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "3ACS",
      GIORNO: "Martedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "3ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "4ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "4ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "4ACS",
      GIORNO: "Mercoledì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "4ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "5ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "5ACS",
      GIORNO: "Lunedì",
      ORA_INIZIO: "20:00",
      ORA_FINE: "20:50",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "5ACS",
      GIORNO: "Giovedì",
      ORA_INIZIO: "18:00",
      ORA_FINE: "18:50",
    },
    {
      MATERIA: "Tecnologie Chimiche Industriali",
      CLASSE: "5ACS",
      GIORNO: "Venerdì",
      ORA_INIZIO: "18:50",
      ORA_FINE: "19:40",
    },
  ],
  // Timpano: [
  //   {
  //     MATERIA: "Telecomunicazioni",
  //     CLASSE: "3AIS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Telecomunicazioni",
  //     CLASSE: "3AIS",
  //     GIORNO: "Martedì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  //   {
  //     MATERIA: "Telecomunicazioni",
  //     CLASSE: "4AIS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Telecomunicazioni",
  //     CLASSE: "4AIS",
  //     GIORNO: "Lunedì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  // ],
  // Ussia: [
  //   {
  //     MATERIA: "Diritto ed Economia",
  //     CLASSE: "2AS",
  //     GIORNO: "Mercoledì",
  //     ORA_INIZIO: "18:00",
  //     ORA_FINE: "18:50",
  //   },
  //   {
  //     MATERIA: "Diritto ed Economia",
  //     CLASSE: "2AS",
  //     GIORNO: "Mercoledì",
  //     ORA_INIZIO: "18:50",
  //     ORA_FINE: "19:40",
  //   },
  // ],
};
